#!/bin/sh

# strip variable data from files
[ -f makeinclude ] && sed -e 's/^#.*/#/' makeinclude > makeinclude.$$ && mv makeinclude.$$ makeinclude
[ -f configure ] && sed -e 's/ (revision .*)$//' configure > configure.$$ && mv configure.$$ configure

RETVAL=0

for f in $1/*
do
	# find local counterpart
	g=`basename $f`
	
	# compare else error 
	diff -u $f $g || RETVAL=1
done

exit $RETVAL