#!/bin/sh

# This file is part of the Grace library (libgrace).
# The Grace library is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, using version 3 of the License.
# You should have received a copy of the GNU Lesser General Public License 
# along with Grace library. If not, see <http://www.gnu.org/licenses/>.

if [ ! -f configure.paths ]; then
  echo "No configure.paths found, please run ./configure" >&2
  exit 1
fi

. ./configure.paths

path_bin="${DESTDIR}$CONFIG_BINPATH"
path_lib="${DESTDIR}$CONFIG_LIBPATH"
path_include="${DESTDIR}$CONFIG_INCLUDEPATH"


if [ ! -d "$path_lib" ]; then
  mkdir -p "$path_lib"
fi

if [ -e /usr/bin/install_name_tool ]; then
  install_name_tool -id $path_lib/libgrace-pcre.dylib ../../lib/libgrace-pcre.dylib
fi

if [ -e ../../lib/libgrace-pcre.dylib ]; then
  cp ../../lib/libgrace-pcre.dylib $path_lib/
else
  cp ../../lib/libgrace-pcre.so "$path_lib/libgrace-pcre.so.1.1"
  cp ../../lib/libgrace-pcre.a "$path_lib/libgrace-pcre.a"
  ln -s "./libgrace-pcre.so.1.1" "$path_lib/libgrace-pcre.so"
fi

