#!/bin/sh

TEST=`echo -n`
if [ -z "$TEST" ]; then
  ECHON="echo -n"
  NHL=""
else
  ECHON="echo"
  NHL="\c"
fi

UN_OS=`uname -o 2>/dev/null || uname`
UN_PROC=`( uname -i 2>/dev/null || uname -p 2>/dev/null || uname -m ) | cut -f1 -d,`

if [ "$UN_OS" = "GNU/Linux" ]; then
  UN_OS="Linux"
fi

if [ "$UN_PROC" = "unknown" ]; then
  if [ "$UN_OS" = "Cygwin" ]; then
    UN_PROC=i386
  fi
fi

ARCH="$UN_OS.$UN_PROC"

appname="$1"
appid="$2"
if [ -z "$appname" ]; then
  if [ -f .appname ]; then appname=`cat .appname`; fi
  if [ -z "$appname" ]; then
    echo "Usage: $0 <appname>" >&2
    exit 1
  fi
fi
if [ -z "$appid" ]; then
  if [ -f .appid ]; then appid=`cat .appid`; fi
fi
if [ -z "$appid" ]; then
  appid="arpa.private.applications.$appname"
fi
echo "  Application: $appname"
echo "  Application-ID: $appid"
rsrc="."
if [ -d rsrc ]; then
  rsrc="rsrc"
fi
$ECHON "* Copying executable...$NHL"
mkdir -p "$appname.app"
mkdir -p "$appname.app/Contents/${ARCH}"
if [ -f "$appname.exe" ]; then
  cp -p "$appname.exe" "$appname.app/Contents/${ARCH}/"
  rm -f "$appname.exe"
  cd "$appname.app"
  rm -f "exec"
  ln -s "Contents/${ARCH}/$appname.exe" exec
  cd ..
  rm -f "$appname"
  ln -s "$appname.app/exec" "$appname"
fi
echo " OK"
$ECHON "* Installing schemas...$NHL"
mkdir -p "$appname.app/Contents/Schemas"
cp -p $rsrc/*.schema.xml "$appname.app/Contents/Schemas/" >/dev/null 2>&1
cp -p $rsrc/*.validator.xml "$appname.app/Contents/Schemas/" >/dev/null 2>&1
echo " OK"
$ECHON "* Installing resource files...$NHL"
mkdir -p "$appname.app/Contents/Resources"
cp -p $rsrc/*.rsrc.xml "$appname.app/Contents/Resources/" >/dev/null 2>&1
cp -p $rsrc/grace.*.xml "$appname.app/Contents/Resources/" >/dev/null 2>&1
cp -p $rsrc/resources.xml "$appname.app/Contents/Resources/" >/dev/null 2>&1
cp -p $rsrc/*.tmpl "$appname.app/Contents/Resources/" >/dev/null 2>&1
cp -p $rsrc/*.txt "$appname.app/Contents/Resources/" >/dev/null 2>&1
cp -p $rsrc/*.*htm* "$appname.app/Contents/Resources/" >/dev/null 2>&1
cp -p $rsrc/*.jpg $rsrc/*.png $rsrc/*.gif $rsrc/*.bmp $rsrc/*.png $rsrc/*.xpm "$appname.app/Contents/Resources/" >/dev/null 2>&1
rm -f $appname.app/Contents/Resources/*.schema.xml >/dev/null 2>&1
echo " OK"
$ECHON "* Installing default configuration...$NHL"
mkdir -p "$appname.app/Contents/Configuration Defaults"
cp -p $rsrc/*.conf.xml "$appname.app/Contents/Configuration Defaults/" >/dev/null 2>&1
echo " OK"
if [ -d tools ]; then
  $ECHON "* Installing tools...$NHL"
  mkdir -p "$appname.app/Contents/Tools"
  cp -p tools/* "$appname.app/Contents/Tools/" >/dev/null 2>&1
  echo " OK"
fi
$ECHON "* Setting bundle metadata...$NHL"
cat > "$appname.app/.meta" << _EOF_
<?xml version="1.0" encoding="utf-8"?>
<metro.directory type="directory/application-bundle" id="1837124781230156">
  <metro.appid>$appid</metro.appid>
</metro.directory>
_EOF_
echo " OK"
