#!/bin/sh

genversion() {
    BRANCH=`hg parents -b --template '{branches}\n'`
	if [ -z "$DISTRO" ]; then
	  DISTRO="generic"
	fi
	
	ACTUALTAG=`hg id | cut -f2 -d" "`
	if [ "$ACTUALTAG" = "$BRANCH" ]; then
	  echo -n "${BRANCH}-${DISTRO}"
	else
	  ACTUALID=`hg id | cut -f1 -d" "`
	  echo -n "${BRANCH}-${DISTRO}-${ACTUALID}"
	fi
	if hg id | cut -f1 -d" " | grep -q "+$"
	then
	    echo "-plus"
	else
	    echo ""
	fi
}

hg id >/dev/null 2>&1 || {
  if [ ! -f version.id ]; then
    echo "% No mercurial repository and no version.id file found" >&2
    exit 1
  fi
  
  BUILD_VERSION=`head -1 < version.id`
  if [ -z "${BUILD_VERSION}" ]; then
    echo "% Format error in version.id file"
    exit 1
  fi
}

FILENAME="$1"

BUILD_USER=`whoami`
BUILD_HOST=`hostname`
BUILD_DATE=`date +%Y-%m-%dT%H:%M:%S`
if [ -z "$BUILD_VERSION" ]; then
  BUILD_VERSION=`genversion`
  echo "$BUILD_VERSION" > version.id
fi
BUILD_SHORTVERSION=`echo "$BUILD_VERSION" | cut -f1 -d-`

if [ -z "$1" ]; then
  echo "% Variables detected:"
  echo "%BUILD_USER%: $BUILD_USER"
  echo "%BUILD_HOST%: $BUILD_HOST"
  echo "%BUILD_DATE%: $BUILD_DATE"
  echo "%BUILD_VERSION: $BUILD_VERSION"
  echo "%BUILD_SHORTVERSION: $BUILD_SHORTVERSION"
  echo
  echo "% Usage: mkversion <filename>"
  echo "         Will build <filename> from <filename>.in"
  exit 1
fi

if [ ! -f "${FILENAME}.in" ]; then
  echo "File ${FILENAME}.in not found"
  exit 1
fi

cat "${FILENAME}.in" | sed -e "s/%BUILD_SHORTVERSION%/${BUILD_SHORTVERSION}/;s/%BUILD_VERSION%/${BUILD_VERSION}/;s/%BUILD_HOST%/${BUILD_HOST}/;s/%BUILD_USER%/${BUILD_USER}/;s/%BUILD_DATE%/${BUILD_DATE}/" \
	> ${FILENAME}

