#!/bin/sh

path_bin=${DESTDIR}/usr/bin
path_lib=${DESTDIR}/usr/lib
path_include=${DESTDIR}/usr/include

if [ ! -d "$path_bin" ]; then
  mkdir -p "$path_bin"
fi

if [ ! -d "$path_lib" ]; then
  mkdir -p "$path_lib"
fi

if [ ! -d "$path_include" ]; then
  mkdir -p "$path_include"
fi

if [ ! -d "$path_include/matrixssl" ]; then
  mkdir -p "$path_include/matrixssl"
fi

cp src/libmatrixsslstatic.a "$path_lib/"
cp *.h src/*.h "$path_include/matrixssl/"

RANLIB=`grep RANLIB < makeinclude | sed -e "s/.* = //"`
if [ ! -z "$RANLIB" ]; then
  $RANLIB "$path_lib/libmatrixsslstatic.a"
fi
