#!/bin/sh

# This file is part of the Grace library, ssl addon (libgrace-ssl).
# The Grace library is free software: you can redistribute it and/or modify it 
# under the terms of the GNU General Public License as published by the Free 
# Software Foundation, using version 3 of the License.
# You should have received a copy of the GNU General Public License along with 
# Grace library. If not, see <http://www.gnu.org/licenses/>.

if [ ! -f configure.paths ]; then
  echo "No configure.paths found, please run ./configure" >&2
  exit 1
fi

. ./configure.paths

path_bin="${DESTDIR}$CONFIG_BINPATH"
path_lib="${DESTDIR}$CONFIG_LIBPATH"
path_include="${DESTDIR}$CONFIG_INCLUDEPATH"


if [ ! -d "$path_bin" ]; then
  mkdir -p "$path_bin"
fi

if [ ! -d "$path_lib" ]; then
  mkdir -p "$path_lib"
fi

if [ ! -d "$path_include" ]; then
  mkdir -p "$path_include"
fi

if [ ! -d "$path_include/matrixssl" ]; then
  mkdir -p "$path_include/matrixssl"
fi

if [ -e /usr/bin/install_name_tool ]; then
  install_name_tool -id $path_lib/libgrace-ssl.dylib ../../lib/libgrace-ssl.dylib
fi
cp ../../lib/libgrace-ssl.* "$path_lib/"
cp ../../include/matrixssl/*.h "$path_include/matrixssl"

