#!/bin/sh
if [ ! -f configure.paths ]; then
  echo "No configure.paths found, please run ./configure" >&2
  exit 1
fi

. ./configure.paths

path_bin="$CONFIG_BINPATH"
path_lib="$CONFIG_LIBPATH"
path_include="$CONFIG_INCLUDEPATH"


if [ ! -d "$path_bin" ]; then
  mkdir "$path_bin"
fi

if [ ! -d "$path_lib" ]; then
  mkdir "$path_lib"
fi

if [ ! -d "$path_include" ]; then
  mkdir "$path_include"
fi

if [ ! -d "$path_include/matrixssl" ]; then
  mkdir "$path_include/matrixssl"
fi

if [ -e /usr/bin/install_name_tool ]; then
  install_name_tool -id $path_lib/libgrace-ssl.dylib ../../lib/libgrace-ssl.dylib
fi
cp ../../lib/libgrace-ssl.* "$path_lib/"
cp ../../include/matrixssl/*.h "$path_include/matrixssl"

