#!/bin/sh

# This file is part of the Grace library (libgrace).
# The Grace library is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, using version 3 of the License.
# You should have received a copy of the GNU Lesser General Public License 
# along with Grace library. If not, see <http://www.gnu.org/licenses/>.

if [ ! -e configure.paths ]; then
  echo "Please run configure first" >&2
  exit 1
fi

. ./configure.paths
mkdir -p ${DESTDIR}${CONFIG_LIBPATH}/grace-configure
mkdir -p ${DESTDIR}${CONFIG_BINPATH}/util-grace
install -m 755 mkconfigure ${DESTDIR}${CONFIG_BINPATH}/util-grace/mkconfigure
cp -p -R autoconfigure/* ${DESTDIR}${CONFIG_LIBPATH}/grace-configure/
