.TH mkapp 1 "04 October 2006" "0.8.12" "mkapp"
.SH NAME
mkapp \- Create a grace supported C++ application or daemon

.SH DESCRIPTION
Used for build automation


.SH SEE ALSO
.BR mkconf (1) 
.BR mkproject (1) 
.SH BUGS
No known bugs at this time. 
.SH AUTHOR
.nf
W.A. van der Meeren (danny@openpanel.com)
.fi
.SH HISTORY
2006 \- The mkapp is part of the libgrace-dev package