#!/bin/sh
if [ ! -f configure.paths ]; then
  echo "No configure.paths found, please run ./configure" >&2
  exit 1
fi

. ./configure.paths

path_bin="$CONFIG_BINPATH"
path_lib="$CONFIG_LIBPATH"
path_include="$CONFIG_INCLUDEPATH"

if [ ! -d "$path_bin" ]; then
  mkdir "$path_bin"
fi

if [ ! -d "$path_lib" ]; then
  mkdir "$path_lib"
fi

if [ ! -d "$path_include" ]; then
  mkdir "$path_include"
fi

if [ ! -d "$path_include/querido" ]; then
  mkdir "$path_include/querido"
fi

echo "Installing library in $path_lib"
if [ -e /usr/bin/install_name_tool ]; then
  install_name_tool -id $path_lib/libquerido.dylib ../../lib/libquerido.dylib
fi
cp ../../lib/libquerido.* "$path_lib/"
echo "Installing headers in $path_include"
cp ../../include/querido/*.h "$path_include/querido/"


