#!/bin/sh

# This file is part of the Grace library (libgrace).
# The Grace library is free software: you can redistribute it and/or modify it
# under the terms of the GNU Lesser General Public License as published by the
# Free Software Foundation, using version 3 of the License.
# You should have received a copy of the GNU Lesser General Public License 
# along with Grace library. If not, see <http://www.gnu.org/licenses/>.

if [ ! -f configure.paths ]; then
  echo "No configure.paths found, please run ./configure" >&2
  exit 1
fi

. ./configure.paths

path_bin="${DESTDIR}$CONFIG_BINPATH"
path_lib="${DESTDIR}$CONFIG_LIBPATH"
path_include="${DESTDIR}$CONFIG_INCLUDEPATH"

if [ ! -d "$path_bin" ]; then
  mkdir -p "$path_bin"
fi

if [ ! -d "$path_lib" ]; then
  mkdir -p "$path_lib"
fi

if [ ! -d "$path_include" ]; then
  mkdir -p "$path_include"
fi

if [ ! -d "$path_include/querido" ]; then
  mkdir -p "$path_include/querido"
fi


echo "Installing library in $path_lib"
if [ -e /usr/bin/install_name_tool ]; then
  install_name_tool -id $path_lib/libquerido.dylib ../../lib/libquerido.dylib
fi
if [ -e ../../lib/libquerido.dylib ]; then
  cp ../../lib/libquerido.dylib $path_lib/
else
  cp ../../lib/libquerido.so "$path_lib/libquerido.so.1.0"
  cp ../../lib/libquerido.a "$path_lib/libquerido.a"
  ln -s "$path_lib/libquerido.so.1.0" "$path_lib/libquerido.so.1"
  ln -s "$path_lib/libquerido.so.1" "$path_lib/libquerido.so"
fi

echo "Installing headers in $path_include"
cp ../../include/querido/*.h "$path_include/querido/"


